import type {
  User,
  Category,
  Problem,
  Cluster,
  Comment,
  Vote,
  StatusChange,
  Notification,
} from "./types"

export const categories = [
  { id: "roads", name: "Дороги", icon: "🛣️", color: "#FF6B6B" },
  { id: "light", name: "Освещение", icon: "💡", color: "#FFD93D" },
  { id: "water", name: "Водоснабжение", icon: "💧", color: "#4D96FF" },
  { id: "trash", name: "Мусор", icon: "🗑️", color: "#6BCB77" },
  { id: "graffiti", name: "Граффити", icon: "🎨", color: "#9D65C9" },
  { id: "buildings", name: "Здания", icon: "🏢", color: "#9E9E9E" },
  { id: "trees", name: "Деревья", icon: "🌳", color: "#4CAF50" },
  { id: "other", name: "Другое", icon: "📌", color: "#795548" }
]

export const users: User[] = [
  {
    id: "user-1",
    name: "Алексей Иванов",
    email: "alex@example.com",
    role: "resident",
    city: "Алматы",
    createdAt: "2025-06-15T10:00:00Z",
    reportsCount: 8,
    votesCount: 24,
  },
  {
    id: "user-2",
    name: "Мария Ким",
    email: "maria@example.com",
    role: "resident",
    city: "Алматы",
    createdAt: "2025-07-20T14:30:00Z",
    reportsCount: 12,
    votesCount: 35,
  },
  {
    id: "user-3",
    name: "Арман Омаров",
    email: "james@example.com",
    role: "resident",
    city: "Алматы",
    createdAt: "2025-08-10T09:15:00Z",
    reportsCount: 3,
    votesCount: 18,
  },
  {
    id: "admin-1",
    name: "Айгуль Админ",
    email: "admin@cityfix.com",
    role: "admin",
    city: "Алматы",
    createdAt: "2025-01-01T00:00:00Z",
    reportsCount: 0,
    votesCount: 0,
  },
]

export const problems: Problem[] = [
  {
    id: "prob-1",
    title: "Большая яма на проспекте Абая",
    description:
      "Опасная яма образовалась недалеко от пересечения с улицей Байтурсынова. Несколько автомобилей получили повреждения. Яма около 2 метров в ширину и увеличивается.",
    categoryId: "roads",
    latitude: 43.238,
    longitude: 76.945,
    address: "пр. Абая, угол ул. Байтурсынова",
    district: "Медеуский район",
    priority: "critical",
    status: "confirmed",
    authorId: "user-1",
    photos: [],
    votesCount: 47,
    commentsCount: 12,
    createdAt: "2025-11-01T08:30:00Z",
    updatedAt: "2025-11-15T14:00:00Z",
    clusterId: "cluster-1",
  },
  {
    id: "prob-2",
    title: "Трещины на дороге возле ЦУМа",
    description:
      "Множественные трещины на дорожном покрытии возле ЦУМа. Становится опасно для велосипедистов и пешеходов.",
    categoryId: "roads",
    latitude: 43.259,
    longitude: 76.947,
    address: "ул. Толе би, угол ул. Фурманова",
    district: "Алмалинский район",
    priority: "critical",
    status: "confirmed",
    authorId: "user-2",
    photos: [],
    votesCount: 32,
    commentsCount: 8,
    createdAt: "2025-11-05T10:15:00Z",
    updatedAt: "2025-11-20T09:00:00Z",
    clusterId: "cluster-1",
  },
  {
    id: "prob-3",
    title: "Прорыв водопровода на улице Жамбыла",
    description:
      "Вода течет из прорванной трубы уже 3 дня. Улица подтапливается, происходит большая потеря воды.",
    categoryId: "water",
    latitude: 43.247,
    longitude: 76.924,
    address: "ул. Жамбыла, угол ул. Наурызбай батыра",
    district: "Бостандыкский район",
    priority: "critical",
    status: "in_progress",
    authorId: "user-2",
    photos: [],
    votesCount: 68,
    commentsCount: 23,
    createdAt: "2025-10-28T16:45:00Z",
    updatedAt: "2025-11-12T11:30:00Z",
    clusterId: "cluster-2",
  },
  {
    id: "prob-4",
    title: "Проблемы с давлением воды на улице Сатпаева",
    description:
      "Очень низкое давление воды в зданиях вдоль улицы Сатпаева между проспектом Аль-Фараби и улицей Жандосова. Страдают многие жители.",
    categoryId: "water",
    latitude: 43.224,
    longitude: 76.909,
    address: "ул. Сатпаева, угол ул. Жандосова",
    district: "Бостандыкский район",
    priority: "medium",
    status: "confirmed",
    authorId: "user-3",
    photos: [],
    votesCount: 21,
    commentsCount: 5,
    createdAt: "2025-11-03T12:00:00Z",
    updatedAt: "2025-11-18T15:45:00Z",
    clusterId: "cluster-2",
  },
  {
    id: "prob-5",
    title: "Не работают фонари на улице Гоголя",
    description:
      "Несколько уличных фонарей не работают уже несколько недель. Очень темно и небезопасно ночью.",
    categoryId: "lighting",
    latitude: 43.254,
    longitude: 76.931,
    address: "ул. Гоголя, угол ул. Пушкина",
    district: "Алмалинский район",
    priority: "medium",
    status: "new",
    authorId: "user-1",
    photos: [],
    votesCount: 15,
    commentsCount: 4,
    createdAt: "2025-11-10T19:20:00Z",
    updatedAt: "2025-11-10T19:20:00Z",
    clusterId: "cluster-3",
  },
  {
    id: "prob-6",
    title: "Переполненные мусорные баки в Центральном парке",
    description:
      "Мусорные баки в Центральном парке постоянно переполнены, особенно по выходным. Привлекает вредителей и создает антисанитарные условия.",
    categoryId: "garbage",
    latitude: 43.257,
    longitude: 76.956,
    address: "Центральный парк культуры и отдыха",
    district: "Медеуский район",
    priority: "medium",
    status: "in_progress",
    authorId: "user-2",
    photos: [],
    votesCount: 34,
    commentsCount: 9,
    createdAt: "2025-10-25T11:00:00Z",
    updatedAt: "2025-11-08T16:30:00Z",
    clusterId: "cluster-4",
  },
  {
    id: "prob-7",
    title: "Сломанная скамейка в парке имени 28 гвардейцев-панфиловцев",
    description:
      "Скамейка в парке сломана и имеет острые края. Потенциальная опасность для посетителей.",
    categoryId: "parks",
    latitude: 43.259,
    longitude: 76.955,
    address: "Парк имени 28 гвардейцев-панфиловцев",
    district: "Медеуский район",
    priority: "low",
    status: "new",
    authorId: "user-3",
    photos: [],
    votesCount: 8,
    commentsCount: 2,
    createdAt: "2025-11-12T14:15:00Z",
    updatedAt: "2025-11-12T14:15:00Z",
    clusterId: "cluster-5",
  },
  {
    id: "prob-8",
    title: "Отключение электричества на проспекте Сейфуллина",
    description:
      "Периодические отключения электроэнергии, затрагивающие предприятия вдоль проспекта. Происходят ежедневно в течение последней недели.",
    categoryId: "electricity",
    latitude: 43.237,
    longitude: 76.897,
    address: "пр. Сейфуллина, угол ул. Тимирязева",
    district: "Ауэзовский район",
    priority: "critical",
    status: "in_progress",
    authorId: "user-1",
    photos: [],
    votesCount: 52,
    commentsCount: 18,
    createdAt: "2025-10-30T07:45:00Z",
    updatedAt: "2025-11-14T10:15:00Z",
    clusterId: "cluster-6",
  },
  {
    id: "prob-9",
    title: "Повреждена остановка автобуса",
    description:
      "Остановка автобуса на проспекте Абая разбита. Стеклянные панели разбиты, скамейка сломана.",
    categoryId: "transport",
    latitude: 43.241,
    longitude: 76.908,
    address: "пр. Абая, ост. 'Дворец спорта'",
    district: "Алмалинский район",
    priority: "low",
    status: "new",
    authorId: "user-2",
    photos: [],
    votesCount: 11,
    commentsCount: 3,
    createdAt: "2025-11-14T16:30:00Z",
    updatedAt: "2025-11-14T16:30:00Z",
    clusterId: "cluster-7",
  },
  {
    id: "prob-10",
    title: "Запах канализации в районе Арбата",
    description:
      "Сильный запах канализации из ливневых стоков. Множество жалоб от близлежащих предприятий и посетителей.",
    categoryId: "sewage",
    latitude: 43.262,
    longitude: 76.947,
    address: "ул. Жибек Жолы, угол ул. Панфилова",
    district: "Алмалинский район",
    priority: "medium",
    status: "confirmed",
    authorId: "user-3",
    photos: [],
    votesCount: 28,
    commentsCount: 7,
    createdAt: "2025-11-06T09:00:00Z",
    updatedAt: "2025-11-19T13:00:00Z",
    clusterId: "cluster-8",
  },
  {
    id: "prob-11",
    title: "Яма на улице Розыбакиева",
    description:
      "Глубокая яма в правом ряду на улице Розыбакиева недалеко от пересечения с проспектом Аль-Фараби. Вызывает пробки и повреждения автомобилей.",
    categoryId: "roads",
    latitude: 43.212,
    longitude: 76.914,
    address: "ул. Розыбакиева, угол пр. Аль-Фараби",
    district: "Бостандыкский район",
    priority: "critical",
    status: "new",
    authorId: "user-1",
    photos: [],
    votesCount: 19,
    commentsCount: 6,
    createdAt: "2025-11-16T08:00:00Z",
    updatedAt: "2025-11-16T08:00:00Z",
    clusterId: "cluster-9",
  },
  {
    id: "prob-12",
    title: "Упавшее дерево блокирует тротуар",
    description:
      "Большое дерево упало и блокирует тротуар на улице Шевченко. Пешеходы вынуждены идти по дороге.",
    categoryId: "parks",
    latitude: 43.249,
    longitude: 76.938,
    address: "ул. Шевченко, угол ул. Курмангазы",
    district: "Алмалинский район",
    priority: "critical",
    status: "confirmed",
    authorId: "user-2",
    photos: [],
    votesCount: 41,
    commentsCount: 11,
    createdAt: "2025-11-13T06:30:00Z",
    updatedAt: "2025-11-17T09:45:00Z",
    clusterId: "cluster-10",
  },
]

export const clusters: Cluster[] = [
  {
    id: "cluster-1",
    categoryId: "roads",
    latitude: 43.2485,
    longitude: 76.946,
    radius: 0.5,
    priority: "critical",
    status: "confirmed",
    problemIds: ["prob-1", "prob-2"],
    complaintsCount: 79,
    district: "Центр города",
    title: "Проблемы с дорогами - Центр",
    createdAt: "2025-11-01T08:30:00Z",
    updatedAt: "2025-11-20T09:00:00Z",
  },
  {
    id: "cluster-2",
    categoryId: "water",
    latitude: 43.2355,
    longitude: 76.9165,
    radius: 0.3,
    priority: "critical",
    status: "in_progress",
    problemIds: ["prob-3", "prob-4"],
    complaintsCount: 89,
    district: "Бостандыкский район",
    title: "Проблемы с водоснабжением - Бостандыкский район",
    createdAt: "2025-10-28T16:45:00Z",
    updatedAt: "2025-11-18T15:45:00Z",
  },
  {
    id: "cluster-3",
    categoryId: "lighting",
    latitude: 43.254,
    longitude: 76.931,
    radius: 0.2,
    priority: "medium",
    status: "new",
    problemIds: ["prob-5"],
    complaintsCount: 15,
    district: "Алмалинский район",
    title: "Освещение - Алмалинский район",
    createdAt: "2025-11-10T19:20:00Z",
    updatedAt: "2025-11-10T19:20:00Z",
  },
  {
    id: "cluster-4",
    categoryId: "garbage",
    latitude: 43.257,
    longitude: 76.956,
    radius: 0.2,
    priority: "medium",
    status: "in_progress",
    problemIds: ["prob-6"],
    complaintsCount: 34,
    district: "Медеуский район",
    title: "Переполненные мусорные баки - Центральный парк",
    createdAt: "2025-10-25T11:00:00Z",
    updatedAt: "2025-11-08T16:30:00Z",
  },
  {
    id: "cluster-5",
    categoryId: "parks",
    latitude: 43.259,
    longitude: 76.955,
    radius: 0.3,
    priority: "low",
    status: "new",
    problemIds: ["prob-7"],
    complaintsCount: 8,
    district: "Медеуский район",
    title: "Обслуживание парков - Парк 28 гвардейцев",
    createdAt: "2025-11-12T14:15:00Z",
    updatedAt: "2025-11-12T14:15:00Z",
  },
  {
    id: "cluster-6",
    categoryId: "electricity",
    latitude: 43.237,
    longitude: 76.897,
    radius: 0.4,
    priority: "critical",
    status: "in_progress",
    problemIds: ["prob-8"],
    complaintsCount: 52,
    district: "Ауэзовский район",
    title: "Отключения электричества - Ауэзовский район",
    createdAt: "2025-10-30T07:45:00Z",
    updatedAt: "2025-11-14T10:15:00Z",
  },
  {
    id: "cluster-7",
    categoryId: "transport",
    latitude: 43.241,
    longitude: 76.908,
    radius: 0.2,
    priority: "low",
    status: "new",
    problemIds: ["prob-9"],
    complaintsCount: 11,
    district: "Алмалинский район",
    title: "Повреждение остановки - пр. Абая",
    createdAt: "2025-11-14T16:30:00Z",
    updatedAt: "2025-11-14T16:30:00Z",
  },
  {
    id: "cluster-8",
    categoryId: "sewage",
    latitude: 43.262,
    longitude: 76.947,
    radius: 0.3,
    priority: "medium",
    status: "confirmed",
    problemIds: ["prob-10"],
    complaintsCount: 28,
    district: "Алмалинский район",
    title: "Проблемы с канализацией - ул. Жибек Жолы",
    createdAt: "2025-11-06T09:00:00Z",
    updatedAt: "2025-11-19T13:00:00Z",
  },
  {
    id: "cluster-9",
    categoryId: "roads",
    latitude: 43.212,
    longitude: 76.914,
    radius: 0.2,
    priority: "critical",
    status: "new",
    problemIds: ["prob-11"],
    complaintsCount: 19,
    district: "Бостандыкский район",
    title: "Проблемы с дорогами - ул. Розыбакиева",
    createdAt: "2025-11-16T08:00:00Z",
    updatedAt: "2025-11-16T08:00:00Z",
  },
  {
    id: "cluster-10",
    categoryId: "parks",
    latitude: 43.249,
    longitude: 76.938,
    radius: 0.2,
    priority: "critical",
    status: "confirmed",
    problemIds: ["prob-12"],
    complaintsCount: 41,
    district: "Алмалинский район",
    title: "Упавшее дерево - ул. Шевченко",
    createdAt: "2025-11-13T06:30:00Z",
    updatedAt: "2025-11-17T09:45:00Z",
  },
]

export const comments: Comment[] = [
  { id: "com-1", problemId: "prob-1", authorId: "user-2", text: "Я попал в эту яму на прошлой неделе и повредил шину. Это требует срочного внимания!", createdAt: "2025-11-02T10:30:00Z" },
  { id: "com-2", problemId: "prob-1", authorId: "user-3", text: "Согласен, с каждым днем становится хуже. Видел, как несколько машин объезжали ее.", createdAt: "2025-11-03T14:15:00Z" },
  { id: "com-3", problemId: "prob-3", authorId: "user-1", text: "Вода затапливает весь квартал. Кто-то должен исправить это как можно скорее.", createdAt: "2025-10-29T08:00:00Z" },
  { id: "com-4", problemId: "prob-3", authorId: "user-3", text: "Я также сообщил об этом в водоканал. Сказали, что пришлют кого-то.", createdAt: "2025-10-30T11:45:00Z" },
  { id: "com-5", problemId: "prob-6", authorId: "user-1", text: "Ситуация становится очень плохой вечером в воскресенье, после того как все покидают парк.", createdAt: "2025-10-26T18:30:00Z" },
  { id: "com-6", problemId: "prob-8", authorId: "user-2", text: "Мой магазин потерял выручку из-за этих отключений. Нам нужно постоянное решение.", createdAt: "2025-10-31T09:15:00Z" },
  { id: "com-7", problemId: "prob-8", authorId: "user-3", text: "В энергокомпании сказали, что работают над модернизацией трансформаторов в этом районе.", createdAt: "2025-11-02T16:00:00Z" },
  { id: "com-8", problemId: "prob-12", authorId: "user-1", text: "Это очень опасно. Родителям с колясками приходится идти по дороге, чтобы обойти это.", createdAt: "2025-11-13T10:00:00Z" },
]

export const votes: Vote[] = [
  { id: "vote-1", problemId: "prob-1", userId: "user-2", createdAt: "2025-11-01T12:00:00Z" },
  { id: "vote-2", problemId: "prob-1", userId: "user-3", createdAt: "2025-11-02T09:00:00Z" },
  { id: "vote-3", problemId: "prob-3", userId: "user-1", createdAt: "2025-10-29T10:00:00Z" },
  { id: "vote-4", problemId: "prob-3", userId: "user-3", createdAt: "2025-10-30T14:00:00Z" },
  { id: "vote-5", problemId: "prob-8", userId: "user-2", createdAt: "2025-11-01T08:00:00Z" },
]

export const statusChanges: StatusChange[] = [
  { id: "sc-1", problemId: "prob-1", fromStatus: "new", toStatus: "confirmed", changedBy: "admin-1", comment: "Подтверждено полевой командой", createdAt: "2025-11-05T10:00:00Z" },
  { id: "sc-2", problemId: "prob-3", fromStatus: "new", toStatus: "confirmed", changedBy: "admin-1", comment: "Чрезвычайная ситуация подтверждена", createdAt: "2025-10-29T14:00:00Z" },
  { id: "sc-3", problemId: "prob-3", fromStatus: "confirmed", toStatus: "in_progress", changedBy: "admin-1", comment: "Ремонтная бригада отправлена", createdAt: "2025-11-05T09:00:00Z" },
  { id: "sc-4", problemId: "prob-6", fromStatus: "new", toStatus: "in_progress", changedBy: "admin-1", comment: "Устанавливаются дополнительные баки", createdAt: "2025-11-01T15:00:00Z" },
  { id: "sc-5", problemId: "prob-8", fromStatus: "new", toStatus: "in_progress", changedBy: "admin-1", comment: "Электрики проводят расследование", createdAt: "2025-11-02T11:00:00Z" },
  { id: "sc-6", problemId: "prob-12", fromStatus: "new", toStatus: "confirmed", changedBy: "admin-1", comment: "Удаление дерева запланировано", createdAt: "2025-11-14T08:00:00Z" },
]

export const notifications: Notification[] = [
  { id: "notif-1", userId: "user-1", title: "Статус обновлен", message: "Ваше сообщение 'Большая яма на проспекте Абая' подтверждено.", read: false, createdAt: "2025-11-05T10:00:00Z", link: "/problem/prob-1" },
  { id: "notif-2", userId: "user-2", title: "Новый комментарий", message: "Кто-то прокомментировал 'Прорыв водопровода на улице Жамбыла'.", read: true, createdAt: "2025-10-30T11:45:00Z", link: "/problem/prob-3" },
  { id: "notif-3", userId: "user-1", title: "Проблема решена поблизости", message: "Проблема в вашем районе решена.", read: false, createdAt: "2025-11-18T09:00:00Z" },
]

export const districts = [
  "Алмалинский район",
  "Ауэзовский район",
  "Бостандыкский район",
  "Жетысуский район",
  "Медеуский район",
  "Наурызбайский район",
  "Турксибский район",
]