import type {
  User,
  Category,
  Problem,
  Cluster,
  Comment,
  Vote,
  StatusChange,
  Notification,
} from "./types"

export const categories: Category[] = [
  { id: "electricity", name: "Electricity", icon: "Zap", color: "#f59e0b" },
  { id: "water", name: "Water Supply", icon: "Droplets", color: "#3b82f6" },
  { id: "roads", name: "Roads & Potholes", icon: "Construction", color: "#ef4444" },
  { id: "garbage", name: "Garbage", icon: "Trash2", color: "#84cc16" },
  { id: "lighting", name: "Street Lighting", icon: "Lightbulb", color: "#eab308" },
  { id: "parks", name: "Parks & Green", icon: "TreePine", color: "#22c55e" },
  { id: "sewage", name: "Sewage", icon: "Waves", color: "#8b5cf6" },
  { id: "transport", name: "Public Transport", icon: "Bus", color: "#06b6d4" },
]

export const users: User[] = [
  {
    id: "user-1",
    name: "Alex Johnson",
    email: "alex@example.com",
    role: "resident",
    city: "San Francisco",
    createdAt: "2025-06-15T10:00:00Z",
    reportsCount: 8,
    votesCount: 24,
  },
  {
    id: "user-2",
    name: "Maria Chen",
    email: "maria@example.com",
    role: "resident",
    city: "San Francisco",
    createdAt: "2025-07-20T14:30:00Z",
    reportsCount: 12,
    votesCount: 35,
  },
  {
    id: "user-3",
    name: "James Wilson",
    email: "james@example.com",
    role: "resident",
    city: "San Francisco",
    createdAt: "2025-08-10T09:15:00Z",
    reportsCount: 3,
    votesCount: 18,
  },
  {
    id: "admin-1",
    name: "Sarah Admin",
    email: "admin@cityfix.com",
    role: "admin",
    city: "San Francisco",
    createdAt: "2025-01-01T00:00:00Z",
    reportsCount: 0,
    votesCount: 0,
  },
]

export const problems: Problem[] = [
  {
    id: "prob-1",
    title: "Large pothole on Market Street",
    description:
      "A dangerous pothole has formed near the intersection of Market and 5th. Multiple cars have been damaged. The pothole is approximately 2 feet wide and growing.",
    categoryId: "roads",
    latitude: 37.784,
    longitude: -122.408,
    address: "Market St & 5th St",
    district: "SoMa",
    priority: "critical",
    status: "confirmed",
    authorId: "user-1",
    photos: [],
    votesCount: 47,
    commentsCount: 12,
    createdAt: "2025-11-01T08:30:00Z",
    updatedAt: "2025-11-15T14:00:00Z",
    clusterId: "cluster-1",
  },
  {
    id: "prob-2",
    title: "Road cracks near Union Square",
    description:
      "Multiple cracks appearing along the road surface near Union Square. Becoming hazardous for cyclists and pedestrians.",
    categoryId: "roads",
    latitude: 37.7879,
    longitude: -122.4074,
    address: "Powell St & Geary St",
    district: "Union Square",
    priority: "critical",
    status: "confirmed",
    authorId: "user-2",
    photos: [],
    votesCount: 32,
    commentsCount: 8,
    createdAt: "2025-11-05T10:15:00Z",
    updatedAt: "2025-11-20T09:00:00Z",
    clusterId: "cluster-1",
  },
  {
    id: "prob-3",
    title: "Broken water main on Valencia",
    description:
      "Water has been leaking from a broken main for 3 days now. The street is flooding and it is wasting a lot of water.",
    categoryId: "water",
    latitude: 37.764,
    longitude: -122.422,
    address: "Valencia St & 18th St",
    district: "Mission",
    priority: "critical",
    status: "in_progress",
    authorId: "user-2",
    photos: [],
    votesCount: 68,
    commentsCount: 23,
    createdAt: "2025-10-28T16:45:00Z",
    updatedAt: "2025-11-12T11:30:00Z",
    clusterId: "cluster-2",
  },
  {
    id: "prob-4",
    title: "Water pressure issues on Mission St",
    description:
      "Very low water pressure in the buildings along Mission St between 16th and 20th. Multiple residents affected.",
    categoryId: "water",
    latitude: 37.765,
    longitude: -122.42,
    address: "Mission St & 19th St",
    district: "Mission",
    priority: "medium",
    status: "confirmed",
    authorId: "user-3",
    photos: [],
    votesCount: 21,
    commentsCount: 5,
    createdAt: "2025-11-03T12:00:00Z",
    updatedAt: "2025-11-18T15:45:00Z",
    clusterId: "cluster-2",
  },
  {
    id: "prob-5",
    title: "Street lights out on Haight Street",
    description:
      "Several street lights have been non-functional for weeks along Haight St between Masonic and Stanyan. Very dark and unsafe at night.",
    categoryId: "lighting",
    latitude: 37.77,
    longitude: -122.446,
    address: "Haight St & Ashbury St",
    district: "Haight-Ashbury",
    priority: "medium",
    status: "new",
    authorId: "user-1",
    photos: [],
    votesCount: 15,
    commentsCount: 4,
    createdAt: "2025-11-10T19:20:00Z",
    updatedAt: "2025-11-10T19:20:00Z",
    clusterId: "cluster-3",
  },
  {
    id: "prob-6",
    title: "Overflowing garbage bins at Dolores Park",
    description:
      "The garbage bins at Dolores Park are consistently overflowing, especially on weekends. Attracting pests and creating an unsanitary environment.",
    categoryId: "garbage",
    latitude: 37.7596,
    longitude: -122.4269,
    address: "Dolores Park",
    district: "Mission",
    priority: "medium",
    status: "in_progress",
    authorId: "user-2",
    photos: [],
    votesCount: 34,
    commentsCount: 9,
    createdAt: "2025-10-25T11:00:00Z",
    updatedAt: "2025-11-08T16:30:00Z",
    clusterId: "cluster-4",
  },
  {
    id: "prob-7",
    title: "Broken park bench in Golden Gate Park",
    description:
      "A park bench near the Conservatory of Flowers is broken and has sharp edges. Potential safety hazard for visitors.",
    categoryId: "parks",
    latitude: 37.7716,
    longitude: -122.4597,
    address: "Golden Gate Park - Conservatory",
    district: "Western Addition",
    priority: "low",
    status: "new",
    authorId: "user-3",
    photos: [],
    votesCount: 8,
    commentsCount: 2,
    createdAt: "2025-11-12T14:15:00Z",
    updatedAt: "2025-11-12T14:15:00Z",
    clusterId: "cluster-5",
  },
  {
    id: "prob-8",
    title: "Power outage on Fillmore",
    description:
      "Intermittent power outages affecting businesses along Fillmore Street. Happening daily for the past week.",
    categoryId: "electricity",
    latitude: 37.785,
    longitude: -122.433,
    address: "Fillmore St & Haight St",
    district: "Western Addition",
    priority: "critical",
    status: "in_progress",
    authorId: "user-1",
    photos: [],
    votesCount: 52,
    commentsCount: 18,
    createdAt: "2025-10-30T07:45:00Z",
    updatedAt: "2025-11-14T10:15:00Z",
    clusterId: "cluster-6",
  },
  {
    id: "prob-9",
    title: "Bus stop shelter damaged",
    description:
      "The bus stop shelter at Geary & Divisadero has been vandalized. Glass panels are shattered and the bench is broken.",
    categoryId: "transport",
    latitude: 37.783,
    longitude: -122.438,
    address: "Geary Blvd & Divisadero St",
    district: "Western Addition",
    priority: "low",
    status: "new",
    authorId: "user-2",
    photos: [],
    votesCount: 11,
    commentsCount: 3,
    createdAt: "2025-11-14T16:30:00Z",
    updatedAt: "2025-11-14T16:30:00Z",
    clusterId: "cluster-7",
  },
  {
    id: "prob-10",
    title: "Sewage smell near Embarcadero",
    description:
      "Strong sewage odor coming from the storm drains along the Embarcadero. Multiple complaints from nearby businesses and tourists.",
    categoryId: "sewage",
    latitude: 37.7935,
    longitude: -122.3935,
    address: "The Embarcadero & Washington St",
    district: "Financial District",
    priority: "medium",
    status: "confirmed",
    authorId: "user-3",
    photos: [],
    votesCount: 28,
    commentsCount: 7,
    createdAt: "2025-11-06T09:00:00Z",
    updatedAt: "2025-11-19T13:00:00Z",
    clusterId: "cluster-8",
  },
  {
    id: "prob-11",
    title: "Pothole on Cesar Chavez",
    description:
      "Deep pothole in the right lane of Cesar Chavez near Guerrero. Causing traffic slowdown and vehicle damage.",
    categoryId: "roads",
    latitude: 37.748,
    longitude: -122.422,
    address: "Cesar Chavez St & Guerrero St",
    district: "Mission",
    priority: "critical",
    status: "new",
    authorId: "user-1",
    photos: [],
    votesCount: 19,
    commentsCount: 6,
    createdAt: "2025-11-16T08:00:00Z",
    updatedAt: "2025-11-16T08:00:00Z",
    clusterId: "cluster-9",
  },
  {
    id: "prob-12",
    title: "Fallen tree blocking sidewalk",
    description:
      "A large tree has fallen and is blocking the sidewalk on Fell Street near Broderick. Pedestrians forced to walk in the road.",
    categoryId: "parks",
    latitude: 37.774,
    longitude: -122.44,
    address: "Fell St & Broderick St",
    district: "Western Addition",
    priority: "critical",
    status: "confirmed",
    authorId: "user-2",
    photos: [],
    votesCount: 41,
    commentsCount: 11,
    createdAt: "2025-11-13T06:30:00Z",
    updatedAt: "2025-11-17T09:45:00Z",
    clusterId: "cluster-10",
  },
]

export const clusters: Cluster[] = [
  {
    id: "cluster-1",
    categoryId: "roads",
    latitude: 37.786,
    longitude: -122.4077,
    radius: 0.5,
    priority: "critical",
    status: "confirmed",
    problemIds: ["prob-1", "prob-2"],
    complaintsCount: 79,
    district: "Downtown",
    title: "Road Damage - Downtown Area",
    createdAt: "2025-11-01T08:30:00Z",
    updatedAt: "2025-11-20T09:00:00Z",
  },
  {
    id: "cluster-2",
    categoryId: "water",
    latitude: 37.7645,
    longitude: -122.421,
    radius: 0.3,
    priority: "critical",
    status: "in_progress",
    problemIds: ["prob-3", "prob-4"],
    complaintsCount: 89,
    district: "Mission",
    title: "Water Issues - Mission District",
    createdAt: "2025-10-28T16:45:00Z",
    updatedAt: "2025-11-18T15:45:00Z",
  },
  {
    id: "cluster-3",
    categoryId: "lighting",
    latitude: 37.77,
    longitude: -122.446,
    radius: 0.2,
    priority: "medium",
    status: "new",
    problemIds: ["prob-5"],
    complaintsCount: 15,
    district: "Haight-Ashbury",
    title: "Street Lighting - Haight-Ashbury",
    createdAt: "2025-11-10T19:20:00Z",
    updatedAt: "2025-11-10T19:20:00Z",
  },
  {
    id: "cluster-4",
    categoryId: "garbage",
    latitude: 37.7596,
    longitude: -122.4269,
    radius: 0.2,
    priority: "medium",
    status: "in_progress",
    problemIds: ["prob-6"],
    complaintsCount: 34,
    district: "Mission",
    title: "Garbage Overflow - Dolores Park",
    createdAt: "2025-10-25T11:00:00Z",
    updatedAt: "2025-11-08T16:30:00Z",
  },
  {
    id: "cluster-5",
    categoryId: "parks",
    latitude: 37.7716,
    longitude: -122.4597,
    radius: 0.3,
    priority: "low",
    status: "new",
    problemIds: ["prob-7"],
    complaintsCount: 8,
    district: "Western Addition",
    title: "Park Maintenance - Golden Gate",
    createdAt: "2025-11-12T14:15:00Z",
    updatedAt: "2025-11-12T14:15:00Z",
  },
  {
    id: "cluster-6",
    categoryId: "electricity",
    latitude: 37.785,
    longitude: -122.433,
    radius: 0.4,
    priority: "critical",
    status: "in_progress",
    problemIds: ["prob-8"],
    complaintsCount: 52,
    district: "Western Addition",
    title: "Power Outages - Fillmore",
    createdAt: "2025-10-30T07:45:00Z",
    updatedAt: "2025-11-14T10:15:00Z",
  },
  {
    id: "cluster-7",
    categoryId: "transport",
    latitude: 37.783,
    longitude: -122.438,
    radius: 0.2,
    priority: "low",
    status: "new",
    problemIds: ["prob-9"],
    complaintsCount: 11,
    district: "Western Addition",
    title: "Bus Stop Damage - Geary",
    createdAt: "2025-11-14T16:30:00Z",
    updatedAt: "2025-11-14T16:30:00Z",
  },
  {
    id: "cluster-8",
    categoryId: "sewage",
    latitude: 37.7935,
    longitude: -122.3935,
    radius: 0.3,
    priority: "medium",
    status: "confirmed",
    problemIds: ["prob-10"],
    complaintsCount: 28,
    district: "Financial District",
    title: "Sewage Issues - Embarcadero",
    createdAt: "2025-11-06T09:00:00Z",
    updatedAt: "2025-11-19T13:00:00Z",
  },
  {
    id: "cluster-9",
    categoryId: "roads",
    latitude: 37.748,
    longitude: -122.422,
    radius: 0.2,
    priority: "critical",
    status: "new",
    problemIds: ["prob-11"],
    complaintsCount: 19,
    district: "Mission",
    title: "Road Damage - Cesar Chavez",
    createdAt: "2025-11-16T08:00:00Z",
    updatedAt: "2025-11-16T08:00:00Z",
  },
  {
    id: "cluster-10",
    categoryId: "parks",
    latitude: 37.774,
    longitude: -122.44,
    radius: 0.2,
    priority: "critical",
    status: "confirmed",
    problemIds: ["prob-12"],
    complaintsCount: 41,
    district: "Western Addition",
    title: "Fallen Tree - Fell Street",
    createdAt: "2025-11-13T06:30:00Z",
    updatedAt: "2025-11-17T09:45:00Z",
  },
]

export const comments: Comment[] = [
  { id: "com-1", problemId: "prob-1", authorId: "user-2", text: "I hit this pothole last week and it damaged my tire. This needs urgent attention!", createdAt: "2025-11-02T10:30:00Z" },
  { id: "com-2", problemId: "prob-1", authorId: "user-3", text: "Agreed, it is getting worse every day. I have seen several cars swerve to avoid it.", createdAt: "2025-11-03T14:15:00Z" },
  { id: "com-3", problemId: "prob-3", authorId: "user-1", text: "The water is flooding the entire block now. Someone needs to fix this ASAP.", createdAt: "2025-10-29T08:00:00Z" },
  { id: "com-4", problemId: "prob-3", authorId: "user-3", text: "I reported this to the water department as well. They said they would send someone.", createdAt: "2025-10-30T11:45:00Z" },
  { id: "com-5", problemId: "prob-6", authorId: "user-1", text: "The situation gets really bad on Sunday evenings after everyone leaves the park.", createdAt: "2025-10-26T18:30:00Z" },
  { id: "com-6", problemId: "prob-8", authorId: "user-2", text: "My shop lost revenue because of these outages. We need a permanent fix.", createdAt: "2025-10-31T09:15:00Z" },
  { id: "com-7", problemId: "prob-8", authorId: "user-3", text: "The power company said they are working on upgrading the transformers in the area.", createdAt: "2025-11-02T16:00:00Z" },
  { id: "com-8", problemId: "prob-12", authorId: "user-1", text: "This is very dangerous. Parents with strollers have to walk in traffic to get around it.", createdAt: "2025-11-13T10:00:00Z" },
]

export const votes: Vote[] = [
  { id: "vote-1", problemId: "prob-1", userId: "user-2", createdAt: "2025-11-01T12:00:00Z" },
  { id: "vote-2", problemId: "prob-1", userId: "user-3", createdAt: "2025-11-02T09:00:00Z" },
  { id: "vote-3", problemId: "prob-3", userId: "user-1", createdAt: "2025-10-29T10:00:00Z" },
  { id: "vote-4", problemId: "prob-3", userId: "user-3", createdAt: "2025-10-30T14:00:00Z" },
  { id: "vote-5", problemId: "prob-8", userId: "user-2", createdAt: "2025-11-01T08:00:00Z" },
]

export const statusChanges: StatusChange[] = [
  { id: "sc-1", problemId: "prob-1", fromStatus: "new", toStatus: "confirmed", changedBy: "admin-1", comment: "Verified by field team", createdAt: "2025-11-05T10:00:00Z" },
  { id: "sc-2", problemId: "prob-3", fromStatus: "new", toStatus: "confirmed", changedBy: "admin-1", comment: "Emergency confirmed", createdAt: "2025-10-29T14:00:00Z" },
  { id: "sc-3", problemId: "prob-3", fromStatus: "confirmed", toStatus: "in_progress", changedBy: "admin-1", comment: "Repair crew dispatched", createdAt: "2025-11-05T09:00:00Z" },
  { id: "sc-4", problemId: "prob-6", fromStatus: "new", toStatus: "in_progress", changedBy: "admin-1", comment: "Additional bins being installed", createdAt: "2025-11-01T15:00:00Z" },
  { id: "sc-5", problemId: "prob-8", fromStatus: "new", toStatus: "in_progress", changedBy: "admin-1", comment: "Electricians investigating", createdAt: "2025-11-02T11:00:00Z" },
  { id: "sc-6", problemId: "prob-12", fromStatus: "new", toStatus: "confirmed", changedBy: "admin-1", comment: "Tree removal scheduled", createdAt: "2025-11-14T08:00:00Z" },
]

export const notifications: Notification[] = [
  { id: "notif-1", userId: "user-1", title: "Status Updated", message: "Your report 'Large pothole on Market Street' has been confirmed.", read: false, createdAt: "2025-11-05T10:00:00Z", link: "/problem/prob-1" },
  { id: "notif-2", userId: "user-2", title: "New Comment", message: "Someone commented on 'Broken water main on Valencia'.", read: true, createdAt: "2025-10-30T11:45:00Z", link: "/problem/prob-3" },
  { id: "notif-3", userId: "user-1", title: "Problem Resolved Nearby", message: "A problem in your area has been resolved.", read: false, createdAt: "2025-11-18T09:00:00Z" },
]

export const districts = [
  "SoMa",
  "Union Square",
  "Mission",
  "Haight-Ashbury",
  "Western Addition",
  "Financial District",
  "Downtown",
  "Castro",
  "Noe Valley",
  "Richmond",
]
